### PR TITLE
Matrix post

### PR DESCRIPTION
**Pull request by rschulman**
This PR adds a new post about the matrix project that happened at Mozfest 2017.

Georgia, happy for any feedback before I hand it over to Alison.

---
This change is [Reviewable](https://reviewable.io/reviews/opentechinstitute/work-blog-backend/3)

### CODE REVIEW

**Comment by georgiamoon** [comment]
*[content/post/matrix-and-oti-at-mozfest.md, line 7 at r1](https://reviewable.io:443/reviews/opentechinstitute/work-blog-backend/3#-Ky2jSE9zDYeDH3QoBt9:-Ky2jSE9zDYeDH3QoBtA:bm3ad8v) ([raw file](https://github.com/opentechinstitute/work-blog-backend/blob/aa09d54a42752747dbb9499d3400860607594e5a/content/post/matrix-and-oti-at-mozfest.md#L7)):*
> The annual internet freedom conference/party [Mozilla Festival](https://mozillafestival.org/) (Mozfest) was this past weekend, and OTI ended up facilitating an astonishing number of sessions. One that I spent some time working on was aimed at the decentralization track of the festival and involved creating a local and portable chat server using the open source Matrix protocol for the use of the Mozfest attendees. Decentralization means different things to different people but in this context I wanted to focus on demonstrating a viable alternative to the use of something like Slack or Google Hangouts that retained the control over the service in the hands of the community using it--the attendees of Mozfest.

At [Mozilla Festival](https://mozillafestival.org) (MozFest for short), the annual open web / internet freedom conference/party, this past weekend, OTI facilitated an astonishing number of sessions [LINK TO OTI POST] ranging from card games to internet measurement. Within the Decentralization space, I organized a local and portable chat server, using Matrix, that was available to attendees as an alternative to something like Slack or Google Hangouts. Decentralization means different things to different people but in this context I wanted to focus on demonstrating a viable alternative that retained the control over the service in the hands of the community using it--the attendees of Mozfest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/work-blog-backend/3)*

**Comment by georgiamoon** [comment]
*[content/post/matrix-and-oti-at-mozfest.md, line 11 at r1](https://reviewable.io:443/reviews/opentechinstitute/work-blog-backend/3#-Ky2l9qpdm4hPTTqvwXA:-Ky2l9qpdm4hPTTqvwXB:b-ptcwbc) ([raw file](https://github.com/opentechinstitute/work-blog-backend/blob/aa09d54a42752747dbb9499d3400860607594e5a/content/post/matrix-and-oti-at-mozfest.md#L11)):*
> ```Markdown
> What is Matrix?
> ---
> [Matrix](https://matrix.org/) is a relatively new protocol for federated transfer of arbitrary data. The fact that it is federated means that Alice can have her own node and Bob can have his and the two of them can still exchange messages. By and large, the matrix protocol is used to exchange real-time chat or images, much like IRC or Slack does, but it has also been used for things such as MIDI control and WebVR. The protocol also implements end to end encryption.
> ```

Might be good here to provide a link or reference to Alice & Bob, so that they are introduced?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/work-blog-backend/3)*

**Comment by georgiamoon** [comment]
I think this is fine, made some small edits, but if we wanted to do a revision on this, it might be helpful to re-frame as more of a tutorial or as a more of an outline of: Goal, trial & error, end output type of story. But for documenting the project I think this is a fine first pass. We might want to do another post that's more detailed about the setup and maybe tied to a github repo with all the configurations etc?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/opentechinstitute/work-blog-backend/3#-:-Ky2mSHOpSvsRS1iczzF:bkkv7kv)*

**Comment by rschulman** [comment]
Comms has signed off. Merging this post.

**Pull request merged**
